env:
  MAVEN_ARGS: -Dgpg.skip=true
  RPMS_OUTPUT_DIR: "$WORKSPACE/generated_rpms"

after:
  onSuccess:
    - description: "Ensure $RPMS_OUTPUT_DIR exists"
      commands:
        - mkdir -p $RPMS_OUTPUT_DIR

    - description: "Create RPM Package"
      commands:
        - ./bin/build.sh

    - description: "List RPMs in $RPMS_OUTPUT_DIR"
      commands:
        - echo "The following Rpms are ready for upload"
        - ls -lah $RPMS_OUTPUT_DIR

    - description: "Publish RPM"
      container: host
      commands:
        - rpm-upload --rpms-dir=$WORKSPACE/generated_rpms/ --repo-name 8_HubSpot
        - rpm-upload --rpms-dir=$WORKSPACE/generated_rpms/ --repo-name aarch64_8_HubSpot
